[package]
name = "dike"
version = "0.2.0"
authors = ["Rijk van Putten <rijk@rijkvp.nl>"]
description = "Parralel code judger"
edition = "2021"

[dependencies]
clap = { version = "3.2", features = ["derive"] }
thiserror = "1.0"
owo-colors = "3.5"
similar = "2.2"
log = "0.4"
env_logger = "0.9"
rand = "0.8"
crossbeam = "0.8"
signal-hook = "0.3"

[profile.release]
lto = true
strip = true
codegen-units = 1
opt-level = 3
